
output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_MODIS_VOLC/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn.pth"

dbn:
 overwrite_model: True
 params:
  #model_type: 'gaussian_relu' "variance_gaussian"
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  #model_type: "variance_gaussian"
  dbn_arch: [2000] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [1] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.00001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["0","1","2","3","4","5","6","7"]
  batch_size: 1000
  epochs: [35] #[40] #[8] #, 1, 1] #, 5] #, 10]

scaler:
 name: "standard"

#S5P_OFFL_L1B_RA_BD5_20190802T170826
#S5P_OFFL_L1B_RA_BD5_20190802T170826
 
data:
 scale_data: True
 pixel_padding: 1
 number_channels: 37
 fill_value: -9999.0
 valid_min: -900.0
 valid_max: 65534.0
 subset_count: 1
 output_subset_count: 500 #8000
 reader_type: "zarr_to_numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []

 files_train: [
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010105.1135.061.2017251212802.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr"]

 files_test: [
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010105.1315.061.2017251212752.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010123.1300.061.2017253123623.pssgrp_000501840459.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010125.1250.061.2017254220019.pssgrp_000501840459.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010127.1235.061.2017255001328.pssgrp_000501840459.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010132.1255.061.2017253164459.pssgrp_000501840459.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010136.1230.061.2017255014157.pssgrp_000501840459.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1245.061.2017254173516.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1250.061.2017254173525.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1235.061.2017255003423.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr"]
 

#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1035.061.2017252022142.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1215.061.2017252022631.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1220.061.2017252022328.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1355.061.2017252022629.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1400.061.2017252022631.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010106.1535.061.2017252023126.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010107.1120.061.2017252073804.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010107.1125.061.2017252073511.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.1025.061.2017253153128.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.1205.061.2017253154231.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.1340.061.2017253171441.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.1345.061.2017253171445.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.1520.061.2017253171344.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010108.2010.061.2017253171412.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1110.061.2017254172942.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1245.061.2017254173516.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1250.061.2017254173525.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010109.1425.061.2017254172820.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1150.061.2017254184545.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1155.061.2017254184316.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1330.061.2017254184518.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1335.061.2017254184322.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1510.061.2017254183921.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1645.061.2017254183745.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.1820.061.2017254183937.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010110.2135.061.2017254184648.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1055.061.2017255003405.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1100.061.2017255003304.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1240.061.2017255003305.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1410.061.2017255003359.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1415.061.2017255003401.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010111.1550.061.2017255003346.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010112.1140.061.2017255012148.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010112.1315.061.2017255012552.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010112.1320.061.2017255012545.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr",
#"/data/nlahaye/remoteSensing/MODIS_MISR_ICELAND_VOLC/MODIS_L1B/tmp/MOD021KM.A2010112.1455.061.2017255012238.EV_1KM_Emissive_1-EV_1KM_Emissive.tifFull_Bands.zarr"]



