
output:
 out_dir: "/content/gdrive/MyDrive/oil_palm_data_science/ML_Test/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn.pth"

dbn:
 subset_training: 300000
 deep_cluster: False
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] #, 'gaussian_relu_dropout', 'gaussian_relu_dropout'] #'variance_gaussian_dropout' "gaussian_dropout"
  dbn_arch: [75] #[2000] [250, 500, 2000] #, 2000]
  gibbs_steps: [5] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] [0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  use_gpu_preprocessing: False
  world_size: 1
  rank: 0
  device_ids: ["0"]
  batch_size: 1000
  epochs: [25] #[8] #, 1, 1] #, 5] #, 10]

scaler:
 name: "standard"

data:
 num_loader_workers: 10
 scale_data: True
 pixel_padding: 1
 number_channels: 4
 fill_value: -9999.0
 valid_min: -10000.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 100
 reader_type: "gtiff"
 reader_kwargs:
  no_arg: ''
 chan_dim: 0
 delete_chans: []
 transform_default:
  chans: []
  transform: []
 
 #only using 300000 random pixels to train - others are left unseen during training
 files_train: [
  "/content/drive/MyDrive/oil_palm_data_science/ucayali_condensed_stacks_2020_h1v1.tiff"]
 files_test: [
  "/content/gdrive/MyDrive/oil_palm_data_science/ucayali_condensed_stacks_2020_h1v1.tiff"]
 
 
