files_train: [
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file100_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file101_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file102_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file103_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file104_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file105_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file106_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file107_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file108_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file109_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file10_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file110_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file111_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file112_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file113_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file114_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file115_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file116_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file117_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file118_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file119_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file11_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file120_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file121_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file122_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file123_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file124_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file125_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file126_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file127_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file128_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file129_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file12_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file130_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file131_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file132_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file133_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file134_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file135_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file136_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file137_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file138_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file139_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file13_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file140_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file141_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file142_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file143_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file144_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file145_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file146_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file147_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file148_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file149_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file14_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file150_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file151_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file152_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file153_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file154_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file155_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file156_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file157_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file158_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file159_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file15_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file160_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file161_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file162_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file163_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file164_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file165_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file166_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file167_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file168_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file169_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file16_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file170_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file171_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file172_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file173_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file174_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file175_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file176_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file177_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file178_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file179_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file17_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file180_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file181_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file182_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file183_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file184_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file185_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file186_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file187_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file188_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file189_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file18_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file190_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file191_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file192_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file193_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file194_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file195_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file196_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file197_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file198_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file199_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file19_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file200_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file201_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file202_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file203_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file204_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file205_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file206_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file207_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file20_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file21_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file22_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file23_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file24_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file25_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file26_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file27_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file28_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file29_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file2_output.data",
#"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file2_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file30_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file31_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file32_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file33_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file34_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file35_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file36_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file37_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file38_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file39_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file3_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file40_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file41_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file42_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file43_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file44_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file45_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file46_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file47_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file48_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file49_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file4_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file50_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file51_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file52_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file53_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file54_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file55_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file56_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file57_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file58_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file59_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file5_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file60_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file61_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file62_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file63_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file64_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file65_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file66_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file67_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file68_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file69_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file6_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file70_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file71_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file72_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file73_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file74_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file75_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file76_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file77_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file78_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file79_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file7_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file80_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file81_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file82_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file83_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file84_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file85_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file86_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file87_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file88_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file89_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file8_output.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file90_output.data",
#"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file91_output.data",
#"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file92_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file93_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file94_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file95_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file96_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file97_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file98_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file99_output.data",
"/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/file9_output.data"]




output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_TROP_SIF_ONLY/"


clustering:
        n_clusters: 20
        branch: 5
        thresh: 1e-15
        pixel_padding: 1
        train_sample_size: 150000
        clustering:
        train: True
        reset_n_clusters: True
        chunks: 4
        model:  

scaler:
 name: "standard"
 scale: True

