files_train: [
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file0_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file0_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file100_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file101_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file102_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file103_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file104_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file105_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file106_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file107_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file108_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file109_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file10_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file110_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file111_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file112_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file113_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file114_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file115_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file116_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file117_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file118_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file119_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file11_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file120_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file121_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file122_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file123_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file124_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file125_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file126_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file127_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file128_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file129_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file12_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file130_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file131_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file132_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file133_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file134_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file135_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file136_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file137_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file138_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file139_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file13_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file140_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file141_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file142_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file143_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file144_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file145_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file146_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file147_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file148_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file149_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file14_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file150_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file151_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file152_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file153_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file154_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file155_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file156_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file157_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file158_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file159_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file15_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file160_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file161_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file162_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file163_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file164_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file165_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file166_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file167_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file168_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file169_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file16_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file170_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file171_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file172_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file173_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file174_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file175_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file176_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file177_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file178_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file179_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file17_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file180_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file181_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file182_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file183_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file184_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file185_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file186_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file187_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file188_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file189_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file18_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file190_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file191_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file192_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file193_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file194_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file195_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file196_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file197_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file198_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file199_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file19_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file1_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file1_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file200_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file201_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file202_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file203_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file204_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file205_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file206_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file207_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file20_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file21_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file22_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file23_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file24_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file25_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file26_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file27_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file28_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file29_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file2_output.data",
#"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file2_output_test.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file30_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file31_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file32_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file33_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file34_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file35_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file36_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file37_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file38_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file39_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file3_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file40_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file41_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file42_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file43_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file44_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file45_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file46_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file47_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file48_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file49_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file4_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file50_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file51_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file52_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file53_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file54_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file55_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file56_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file57_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file58_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file59_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file5_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file60_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file61_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file62_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file63_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file64_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file65_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file66_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file67_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file68_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file69_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file6_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file70_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file71_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file72_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file73_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file74_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file75_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file76_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file77_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file78_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file79_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file7_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file80_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file81_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file82_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file83_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file84_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file85_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file86_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file87_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file88_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file89_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file8_output.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file90_output.data",
#"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file91_output.data",
#"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file92_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file93_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file94_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file95_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file96_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file97_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file98_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file99_output.data",
"/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/file9_output.data"]




output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_L2_TROP_MOD/"


clustering:
        n_clusters: 20
        branch: 5
        thresh: 1e-15
        pixel_padding: 1
        train_sample_size: 150000
        clustering:
        train: True
        reset_n_clusters: True
        chunks: 4
        model:  

scaler:
 name: "standard"
 scale: True

