output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_PALM_OIL_3/"


clustering:
        n_clusters: 100
        branch: 5
        thresh: 1e-5
        pixel_padding: 1
        train_sample_size: 100000 #000
        clustering:
        train: True
        reset_n_clusters: True
        model:

scaler:
 name: "standard_dask"
 scale: True


files_train: ["/data/nlahaye/output/Learnergy/DBN_PALM_OIL_3/file0_output_test.data"]

files_test: ["/data/nlahaye/output/Learnergy/DBN_PALM_OIL_3/file0_output_test.data"]

