
data:
 pixel_padding: 1
 number_channels: 43
 fill_value: -9999.0
 valid_min: -100.0
 valid_max: 100000000
 subset_count: 1
 output_subset_count: 10
 reader_type: "numpy"
 reader_kwargs:
  no_arg: "no_arg"
 chan_dim: 0
 delete_chans: [26, 44]
 transform_default:
  chans: []
  transform: []
 files_train: ["/data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS/viirs_modis_20220322_114800.npy", 
 "/data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS/viirs_modis_20220323_113000.npy"]
 files_test: ["/data/nlahaye/remoteSensing/GERD_DAM/MODIS_VIIRS/viirs_modis_20220325_105400.npy"]
 

output:
 out_dir: "/data/nlahaye/output/Learnergy/DBN_VIIRS_MODIS/"
 training_output: "output.data"
 training_mse: "rec_mse.data"
 testing_output: "output_test.data"
 testing_mse: "rec_mse_test.data"
 model: "dbn.pth"

dbn:
 overwrite_model: True
 params:
  model_type: ["gaussian_selu"] 
  dbn_arch: [2000] #[250, 500, 2000] #, 2000]
  gibbs_steps: [3] #, 7, 7] #, 10] #, 25]
  learning_rate: [0.0001] #, 0.0001, 0.0001] #, 0.01] #, 0.01]
  momentum: [0.95] #, 0.95, 0.95] #, 0.95] #, 0.95]
  decay: [0.0001] #, 0.0001, 0.0001] #, 0.0001] #, 0.0001]
  temp: [1.0] #, 1.0, 1.0] ##[0.9, 0.75, 0.5] #, 1.0] #, 0.5] #, 0.5] 
  nesterov_accel: [True]
  normalize_learnergy: [False]
  batch_normalize: [False]

 training:
  use_gpu: True
  world_size: 1
  rank: 0
  device_ids: [0,1,2,3,4,5,6,7]
  batch_size: 10000
  epochs: [100] #[8] #, 1, 1] #, 5] #, 10]
