

training_config: "../../config/model/train_model_PV_Gambia.yaml"
context_config: "../../config/postprocess/pv_mapping_geotiff_gen_test_road_masked_full_iter2.yaml"

run_uid: "PV_Map_Tiered_Mask"

config_dir: "../../config/"

reuse_gtiffs: False

update_inputs: False
 
input_dir: "/data/nlahaye/remoteSensing/PV_Mapping/Full_Area/"
input_pattern: "pleides_RGBNED_*tif"
 
tile_tiers: [1024, 512, 256, 128, 64, 32]

context_classes: "pv_panel"

