
gen_from_geotiffs: false

data:
 clust_reader_type: "zarr_to_numpy"
 reader_kwargs:
   no_arg: "no_arg" 
 subset_inds: [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
 create_separate: false
   

 gtiff_data: [
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNK.2022253T183158.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNL.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNM.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022244T183720.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022252T183742.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TNN.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022247T181954.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPK.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022245T183151.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPL.2022253T183134.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPM.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022245T183127.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TPN.2022253T183110.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQK.2022246T182546.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQK.2022247T181954.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQL.2022246T182522.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQL.2022247T181930.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQM.2022246T182458.v2.0.B01.tif",
"/data/nlahaye/remoteSensing/LANDSAT_BENCHMARK/subset/HLS.L30.T11TQM.2022247T181907.v2.0.B01.tif"
]

  
 cluster_fnames: [
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNK.2022246T182546.v2.0.B01.tif.clust.data_78293clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNK.2022253T183158.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNL.2022245T183151.v2.0.B01.tif.clust.data_78298clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNL.2022246T182522.v2.0.B01.tif.clust.data_68540clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNL.2022253T183134.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNM.2022245T183127.v2.0.B01.tif.clust.data_78298clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNM.2022246T182458.v2.0.B01.tif.clust.data_68540clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNN.2022244T183720.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNN.2022245T183127.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNN.2022246T182458.v2.0.B01.tif.clust.data_68540clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNN.2022252T183742.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TNN.2022253T183110.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPK.2022245T183151.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPK.2022246T182546.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPK.2022247T181954.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPK.2022253T183134.v2.0.B01.tif.clust.data_78293clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPL.2022245T183151.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPL.2022246T182522.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPL.2022247T181930.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPL.2022253T183134.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPM.2022245T183127.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPM.2022246T182458.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPM.2022247T181930.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPM.2022253T183110.v2.0.B01.tif.clust.data_78293clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPN.2022245T183127.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPN.2022246T182458.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TPN.2022253T183110.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQK.2022246T182546.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQK.2022247T181954.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQL.2022246T182522.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQL.2022247T181930.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQM.2022246T182458.v2.0.B01.tif.clust.data_78299clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQM.2022247T181907.v2.0.B01.tif.clust.data_78295clusters.zarr",
"/data/nlahaye/output/Learnergy/DBN_LANDSAT_MULTI_LAYER_PL/HLS.L30.T11TQM.2022247T181907.v2.0.B01.tif.clust.data_78299clusters.zarr"
]


context:
 apply_context: False
 clusters: [2398, 2061, 315] #i.e. smoke clusters
 name: "smoke" #i.e. smoke
 compare_truth: false
 generate_union: false
 cluster_dependencies: 
  129: [42,346]
  289: [42,346]
  354: [42,346]
  181: [42,346]



