
output:
 out_dir: '/data/nlahaye/output/GOES_LA_SMOKE/'
 class_name: ['smoke_background', "smoke"]

data:
 min_thresh: 0.0
 label_gtiffs: [
[
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250060001192_e20250060003565_c20250060004002.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250061706170_e20250061708543_c20250061708594.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250062206170_e20250062208543_c20250062208579.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250072001172_e20250072003545_c20250072003585.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250072101172_e20250072103545_c20250072103578.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250080001172_e20250080003545_c20250080003581.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250082206173_e20250082208546_c20250082208585.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250090006174_e20250090008547_c20250090008590.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250091601175_e20250091603548_c20250091603585.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250092206175_e20250092208548_c20250092208589.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250100006175_e20250100008548_c20250100009004.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250101636176_e20250101638549_c20250101638587.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250102206177_e20250102208550_c20250102208580.smoke.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250111636178_e20250111638551_c20250111638584.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250112206178_e20250112208551_c20250112208589.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250120006179_e20250120008552_c20250120008589.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250122006180_e20250122008553_c20250122008584.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250130006180_e20250130008553_c20250130008592.background.shp",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/tags/GOES_TAGS/OR_ABI-L1b-RadC-M6C01_G18_s20250132106182_e20250132108555_c20250132108586.background.shp",
]
]






 clust_gtiffs: [
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250060001192_e20250060003565_c20250060004002.tif.clust.data_76896clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250061701170_e20250061703543_c20250061703581.tif.clust.data_76899clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250062201170_e20250062203543_c20250062203580.tif.clust.data_76899clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250072006172_e20250072008545_c20250072008582.tif.clust.data_76899clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250072101172_e20250072103545_c20250072103578.tif.clust.data_76899clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250080001172_e20250080003545_c20250080003581.tif.clust.data_76899clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250082206173_e20250082208546_c20250082208585.tif.clust.data_76899clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250090006174_e20250090008547_c20250090008590.tif.clust.data_76895clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250091601175_e20250091603548_c20250091603585.tif.clust.data_76895clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250092206175_e20250092208548_c20250092208589.tif.clust.data_76898clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250100006175_e20250100008548_c20250100009004.tif.clust.data_76896clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250101636176_e20250101638549_c20250101638587.tif.clust.data_76898clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250102206177_e20250102208550_c20250102208580.tif.clust.data_76899clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250111636178_e20250111638551_c20250111638584.tif.clust.data_76898clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250112206178_e20250112208551_c20250112208589.tif.clust.data_76899clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250120006179_e20250120008552_c20250120008589.tif.clust.data_76896clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250122106180_e20250122108553_c20250122108592.tif.clust.data_76899clusters.zarr.full_geo.tif",

"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250130006180_e20250130008553_c20250130008592.tif.clust.data_76887clusters.zarr.full_geo.tif",
"/data/nlahaye/SIT_FUSE_Geo/GOES_LA_SMOKE/OR_ABI-L1b-RadC-M6C01_G18_s20250132106182_e20250132108555_c20250132108586.tif.clust.data_76899clusters.zarr.full_geo.tif",

]


