name: sit_fuse
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.8
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blas=2.116
  - blas-devel=3.9.0
  - blosc=1.21.5
  - bokeh=3.4.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorcet=3.1.0
  - contourpy=1.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.2
  - cytoolz=0.12.3
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - datashader=0.16.1
  - distributed=2024.5.0
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.14.0
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.3.1
  - gdal=3.9.0
  - geos=3.12.1
  - geotiff=1.7.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hupper=1.12.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - jinja2=3.1.4
  - json-c=0.17
  - kealib=1.5.3
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=16.0.0
  - libarrow-acero=16.0.0
  - libarrow-dataset=16.0.0
  - libarrow-substrait=16.0.0
  - libblas=3.9.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgdal=3.9.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libparquet=16.0.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.5
  - minizip=4.0.5
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multipledispatch=0.6.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - nspr=4.35
  - nss=3.100
  - numba=0.59.1
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.2
  - param=2.1.0
  - partd=1.4.2
  - pastedeploy=3.1.0
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - plaster=1.0
  - plaster_pastedeploy=0.7
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.4.0
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pyarrow=16.0.0
  - pyarrow-core=16.0.0
  - pyarrow-hotfix=0.6
  - pyct=0.5.0
  - pyramid=2.0.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - rapids=0.0.1
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - s2n=1.4.13
  - scipy=1.13.0
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - spdlog=1.13.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.12.0
  - tblib=3.0.0
  - tiledb=2.23.0
  - tk=8.6.13
  - toolz=0.12.1
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tornado=6.4
  - translationstring=1.4
  - typing_extensions=4.11.0
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.8
  - urllib3=2.2.1
  - venusian=3.1.0
  - webob=1.8.7
  - wheel=0.43.0
  - xarray=2024.5.0
  - xarray-spatial=0.4.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zope.deprecation=4.4.0
  - zope.interface=6.3
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - affine==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - astropy==6.1.0
      - astropy-iers-data==0.2024.5.13.0.30.12
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beartype==0.18.5
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - byol-pytorch==0.8.0
      - cachetools==5.3.3
      - captum==0.7.0
      - cffi==1.16.0
      - cfgv==3.4.0
      - cftime==1.6.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - comm==0.2.2
      - configobj==5.0.8
      - cycler==0.12.1
      - dask-glm==0.3.2
      - dask-ml==2024.4.4
      - dbfread==2.0.7
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diplib==3.4.3
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - donfig==0.8.1.post0
      - einops==0.8.0
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fiona==1.9.6
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - geocube==0.5.2
      - geographiclib==2.0
      - geopandas==0.14.4
      - geopy==2.4.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - gputil==1.4.0
      - grpcio==1.63.0
      - h11==0.14.0
      - h5py==3.11.0
      - healpy==1.16.6
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - identify==2.5.36
      - imageio==2.34.1
      - ipykernel==6.29.4
      - ipython==8.24.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - markdown==3.6
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.6.5
      - nodeenv==1.8.0
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - odc-geo==0.4.5
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - pooch==1.8.1
      - pre-commit==3.7.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pyerfa==2.0.1.4
      - pygments==2.18.0
      - pyhdf==0.11.4
      - pykdtree==1.3.12
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyresample==1.28.3
      - python-json-logger==2.0.7
      - pytorch-lightning==2.2.4
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rasterio==1.3.10
      - referencing==0.35.1
      - regionmask==0.12.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rioxarray==0.15.5
      - rpds-py==0.18.1
      - rsa==4.9
      - safetensors==0.4.3
      - schedulefree==1.2.5
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - send2trash==1.8.3
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - shapely==2.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - snuggs==1.4.7
      - soupsieve==2.5
      - sparse==0.15.1
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.5.10
      - tinycss2==1.3.0
      - torchmetrics==1.4.0.post0
      - torchsummary==1.5.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - torchinfo==1.8.0
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - virtualenv==20.26.2
      - wandb==0.17.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - x-transformers==1.27.22
      - yarl==1.9.4
      - zarr==2.18.0
      - git+https://github.com/Clay-foundation/model.git
      - git+https://github.com/nlahaye/I-JEPA.git
      - git+https://github.com/nlahaye/learnergy.git@module_list_update
      - git+https://github.com/nlahaye/x-transformers.git
      - git+https://github.com/nlahaye/SIT_FUSE.git
      - git+https://github.com/nlahaye/vit-pytorch.git
      - git+https://github.com/nlahaye/pytorch-segmentation.git
      - git+https://github.com/nlahaye/pixel-level-contrastive-learning.git

