name: sit_fuse
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - blas
  - blas-devel
  - blosc
  - bokeh
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - charset-normalizer
  - click
  - cloudpickle
  - colorcet
  - contourpy
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-opencl
  - cuda-runtime
  - cuda-version
  - cytoolz
  - dask
  - dask-core
  - dask-expr
  - datashader
  - distributed
  - expat
  - ffmpeg
  - filelock
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - fsspec
  - gdal
  - geos
  - geotiff
  - gflags
  - giflib
  - glog
  - gmp
  - gmpy2
  - gnutls
  - hdf4
  - hdf5
  - hupper
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - jinja2
  - json-c
  - kealib
  - keyutils
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libhwloc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - liblapacke
  - libllvm14
  - libnetcdf
  - libnghttp2
  - libnpp
  - libnsl
  - libnvjitlink
  - libnvjpeg
  - libparquet
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libutf8proc
  - libuuid
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - llvmlite
  - locket
  - lz4
  - lz4-c
  - lzo
  - markupsafe
  - minizip
  - mkl
  - mkl-devel
  - mkl-include
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multipledispatch
  - ncurses
  - nettle
  - networkx
  - nspr
  - nss
  - numba
  - numpy
  - openh264
  - openjpeg
  - openssl
  - orc
  - packaging
  - pandas
  - param
  - partd
  - pastedeploy
  - pcre2
  - pillow
  - pip
  - pixman
  - plaster
  - plaster_pastedeploy
  - poppler
  - poppler-data
  - postgresql
  - proj
  - psutil
  - pthread-stubs
  - pyarrow
  - pyarrow-core
  - pyarrow-hotfix
  - pyct
  - pyramid
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytorch-cuda
  - pytorch-mutex
  - pytz
  - pyyaml
  - rapids
  - re2
  - readline
  - requests
  - s2n
  - scipy
  - setuptools
  - six
  - snappy
  - sortedcontainers
  - spdlog
  - sqlite
  - tbb
  - tblib
  - tiledb
  - tk
  - toolz
  - torchaudio
  - tornado
  - translationstring
  - typing_extensions
  - tzcode
  - tzdata
  - uriparser
  - urllib3
  - venusian
  - webob
  - wheel
  - xarray
  - xarray-spatial
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - zict
  - zipp
  - zlib
  - zope.deprecation
  - zope.interface
  - zstd
  - pip:
      - absl-py
      - accelerate
      - affine
      - aiohttp
      - aiosignal
      - anyio
      - appdirs
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asciitree
      - astropy
      - astropy-iers-data
      - asttokens
      - async-lru
      - attrs
      - babel
      - beartype
      - beautifulsoup4
      - bleach
      - byol-pytorch
      - cachetools
      - captum
      - cffi
      - cfgv
      - cftime
      - click-plugins
      - cligj
      - comm
      - configobj
      - cycler
      - dask-glm
      - dask-ml
      - dbfread
      - debugpy
      - decorator
      - defusedxml
      - diplib
      - distlib
      - docker-pycreds
      - docstring-parser
      - donfig
      - einops
      - executing
      - fasteners
      - fastjsonschema
      - fiona
      - fonttools
      - fqdn
      - frozenlist
      - geocube
      - geographiclib
      - geopandas
      - geopy
      - gitdb
      - gitpython
      - google-auth
      - gputil
      - grpcio
      - h11
      - h5py
      - healpy
      - httpcore
      - httpx
      - huggingface-hub
      - identify
      - imageio
      - importlib-resources
      - ipykernel
      - ipython
      - ipywidgets
      - isoduration
      - jedi
      - joblib
      - json5
      - jsonargparse
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - kiwisolver
      - kornia
      - kornia-rs
      - lazy-loader
      - learnergy
      - lightning
      - lightning-utilities
      - markdown
      - matplotlib
      - matplotlib-inline
      - mistune
      - multidict
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - netcdf4
      - nodeenv
      - notebook
      - notebook-shim
      - numcodecs
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-cufile-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-cusparselt-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvshmem-cu12
      - nvidia-nvtx-cu12
      - odc-geo
      - opencv-python
      - overrides
      - pandocfilters
      - parso
      - pexpect
      - platformdirs
      - pooch
      - pre-commit
      - prometheus-client
      - prompt-toolkit
      - protobuf
      - ptyprocess
      - pure-eval
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pyerfa
      - pygments
      - pyhdf
      - pykdtree
      - pyparsing
      - pyproj
      - pyresample
      - python-box
      - python-json-logger
      - pytorch-lightning
      - pyzmq
      - qtconsole
      - qtpy
      - rasterio
      - referencing
      - regionmask
      - rfc3339-validator
      - rfc3986-validator
      - rioxarray
      - rpds-py
      - rsa
      - safetensors
      - schedulefree
      - scikit-image
      - scikit-learn
      - send2trash
      - sentry-sdk
      - setproctitle
      - shapely
      - smmap
      - sniffio
      - snuggs
      - soupsieve
      - sparse
      - stack-data
      - sympy
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - terminado
      - threadpoolctl
      - tifffile
      - timm
      - tinycss2
      - torch
      - torchinfo
      - torchmetrics
      - torchsummary
      - torchvision
      - tqdm
      - traitlets
      - triton
      - types-python-dateutil
      - typeshed-client
      - uri-template
      - virtualenv
      - vit-pytorch
      - wandb
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - werkzeug
      - widgetsnbextension
      - yarl
      - zarr
      - git+https://github.com/Clay-foundation/model.git
      - git+https://github.com/nlahaye/I-JEPA.git
      - git+https://github.com/nlahaye/x-transformers.git
      - git+https://github.com/nlahaye/SIT_FUSE.git
      - git+https://github.com/nlahaye/vit-pytorch.git
      - git+https://github.com/nlahaye/pytorch-segmentation.git
      - git+https://github.com/nlahaye/pixel-level-contrastive-learning.git
prefix: /home/nlahaye/miniforge3/envs/sit_fuse
