

data:

 contour_filename: ["/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_02_20190806_1851_1900_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif.Contours3884.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_05_20190806_2033_2039_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif.Contours2084.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours414.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_08_20190806_2249_2259_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif.Contours104.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours112.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_02_20190809_0120_0121_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours67.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours140.tif"]

 filename: ["/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_02_20190806_1851_1900_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_05_20190806_2033_2039_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_08_20190806_2249_2259_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_02_20190809_0120_0121_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.full_geo.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.full_geo.tif"]
 mask_filename: ["/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_02_20190806_1851_1900_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_05_20190806_2033_2039_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_06_20190806_2153_2156_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_08_20190806_2249_2259_V01_georeferenced.tif.npy.clustoutput.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981720_07_20190808_0055_0103_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_02_20190809_0120_0121_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif",
"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981719_07_20190806_2226_2231_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif"]
 reader_type: "gtiff"
 reader_kwargs:
  None:

#"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_01_20190809_0113_0117_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours78.tif",
##"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_05_20190809_0219_0226_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif"]
##"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_01_20190809_0113_0117_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif.Contours78.tif",
###"/data/nlahaye/output/Learnergy/DBN_MASTER/MASTERL1B_1981721_05_20190809_0219_0226_V01_georeferenced.tif.npy.clustoutput_test.data_5000clusters.zarr.smoke.tif"]
 
remove_singles: True
write_geotiff: True

